swagger: "2.0"
info:
  description: This is the swagger file that goes with our server code
  version: "1.0.0"
  title: Swagger REST Article
consumes:
  - "application/json"
produces:
  - "application/json"

basePath: "/api"

# Paths supported by the server application
paths:
  /efemerides:
    get:
      operationId: "ephemeris.get"
      tags:
        - "Ephemeris"
      summary: "The ephemeris data structure supported by the server application"
      description: "Get the day event and month ephemeris"
      parameters:
        - name: day
          description: Day to find.
          in: query
          type: string
          required: true
      responses:
        200:
          description: "Successful getting event operation"
          schema:
            type: "array"
            items:
              properties:
                hoy:
                  type: "string"
                mes:
                  type: "array"
